##############################
# ESMF/8 Dockerfile          #
##############################

# Use the ESCOMP centos8 base - this is a base install of CentOS, plus NetCDF/HDF5/PNetCDF/MPICH
FROM escomp/base-centos8

# Install ESMF (not yet done):
